### ISSUE TITLE
SMM: Provide alternative to OpenConnectionForKey which doesn't open the connection.

### ISSUE THREAD

**Issue by vyrotek** [Azure/elastic-db-tools#114]
As we experimented with working around the issue noted in #112 we discovered an additional and somewhat subtle performance problem when using OpenConnectionForKey with a DbContext from EF6.

The method works fine for a traditional workflow because you can ask for the connection just before you need it and dispose of it immediately when you're done. For example:
```
using (var conn = map.OpenConnectionForKey("shard","connstring"))
{
    // query
}
```

But if you use it with Entity Framework you must provide the DbContext Constructor the SqlConnection. (Note, only EF6+ supports providing an already Open SqlConnection). For Example:

```
public ExampleDB(map, shard, connString) // DbContext Constructor
    : base(new EntityConnection(workspace, map.OpenConnectionForKey(shard,connString), true), true)
{
}
```

This will work but may cause unexpected long-living connections. Normally it's safe to new-up your DbContext early in your code and perform an actual LINQ query later further down. EF handles opening and closing the connection only when needed. But in this case you have an Open connection for the whole lifetime of the DbContext which can quickly lead to running out of available connections in the pool! (In our case, we are using AutoFac and injecting multiple services into various constructors which all need their own references to DbContext and ended up with 10+ long-lasting open connections for one object! This quickly consumed the whole pool once there was concurrent load.)

Ideally the SSM should provide a way to get a SqlConnection that isn't already open and either require the consumer to open it themselves before usage or provide a Options parameter to indicate the behavior you want.

Our current work around is to immediately close the connection received before giving it to the DbContext constructor. Not ideal, but it works.

**Comment by jaredmoo** [comment]
We are unlikely to implement such an API. The problem with this workaround is that it if you ever move mappings while the app is running then you can end up connecting to the wrong shard. When you call `OpenConnectionForKey` with `ConnectionOptions.Validate`, SMM will execute a quick sql query against that shard that validates that the app's cached mapping is still up-to-date. If validation fails then we refresh the mapping from the central SMM database and re-connect (to the new shard). This is how we guarantee that we connect to the correct shard. If you close the connection, then when you re-open it later the mappings may have changed in the meantime without you realizing.

There may be a way in EF's connection factory logic to provider your own custom connection-opening logic that delegates to `OpenConnectionForKey`. Take a look at `IDbProviderFactoryResolver`, but beware that it's pretty abstract and convoluted stuff (IMO).

Is it possible to change your factory methods to return `Func<DbContext>` instead of just `DbContext`? That way each of your components can create short-lived DbContexts on demand instead of needing to hold a single long-lived DbContext. This is what we do in the [Elastic Database Jobs service ](https://azure.microsoft.com/en-us/documentation/articles/sql-database-elastic-jobs-overview/) code and follows the EF best practice of keeping DbContexts around for the shortest time possible.

**Comment by vyrotek** [comment]
Ah, thank you! This is great insight into the design decision behind that behavior. We hadn't considered this scenario since we don't support moving shards and changing mappings. Each customer in our system immediately gets their own shard forever.

I did attempt to research the functionality you described with IDbProviderFactoryResolver but didn't get too far. We already have a very heavily modified EF implementation so that might easily implemented.

The lazy-request Func<DbContext> approach would probably be the best if we weren't trying to convert a large existing code-base. I will definitely keep this in mind for new stuff.

**Comment by jaredmoo** [comment]
If you don't support moving shards then your workaround should be fine although opening and closing connections is obviously a little wasteful. When we have the API from #112 implemented you can potentially just use look up the mapping yourself from the cache and then use the ShardLocation to manually build the connection string. This will avoid the unnecessary open & close.

For now you can also use `OpenConnectionForKey(key, ConnectionOptions.None)` to avoid the unnecessary validation.

**Comment by jaredmoo** [comment]
Closing this issue since we don't want to support such an API and there are alternatives to solve your scenario. Thanks again for the feedback!
