### ISSUE TITLE
The designer must create an instance of type 'System.Data.Common.DbCommand' but it cannot because the type is declared as abstract.

### ISSUE THREAD

**Issue by testaran** [Azure/elastic-db-tools#72]
I have downloaded the latest version of the source code but when I try to open the MultiShardCommand class I have the following exception:

The designer must create an instance of type 'System.Data.Common.DbCommand' but it cannot because the type is declared as abstract.

This is pretty weird since this error is usually raised only when dealing with UI components. Any idea how to solve this issue?

BR

Andrea

**Comment by jaredmoo** [comment]
I get the same issue.

![image](https://cloud.githubusercontent.com/assets/3248887/10699564/71bce416-796c-11e5-970d-74979f26506f.png)

Visual Studio insists on opening the file with the designer. You can see this in the csproj. Even if the subtype is manually removed, VS adds it back again when it loads the project.

    <Compile Include="Query\MultiShardCommand.cs">
      <SubType>Component</SubType>
    </Compile>

How to workaround this issue: select "CSharp editor" as the default editor. This seems to change the VS settings on your machine, so the file will be opened properly but only for you.
http://stackoverflow.com/questions/3870990/how-to-stop-visual-studio-from-opening-my-winforms-controls-in-the-designer

How to fix this issue: looks like the only permanent fix is to add the below attribute to the file. See http://stackoverflow.com/questions/6256327/vs-2010-setting-non-gui-class-file-as-component

  [System.ComponentModel.DesignerCategory("Code")]

**Comment by raveeram** [comment]
This is because MultiShardCommand inherits from Dbcommand which in turn from Component. I guess we have to right click and "view code" for now.

Thanks,
Rakesh
Sent from my phone

On Oct 23, 2015, at 10:14 AM, Jared Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


I get the same issue.

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f3248887%2f10699564%2f71bce416-796c-11e5-970d-74979f26506f.png&data=01%7c01%7craveeram%40microsoft.com%7c1ec4dc59d854489ab8f108d2dbcd7127%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=TTukUKYLphOVPSwwSQK74C5RVR%2b6VGazxy7ZzW8KIxY%3d>

Visual Studio insists on opening the file with the designer. You can see this in the csproj. Even if the subtype is manually removed, VS adds it back again when it loads the project.

<Compile Include="Query\MultiShardCommand.cs">
  <SubType>Component</SubType>
</Compile>


How to workaround this issue: select "CSharp editor" as the default editor. This seems to change the VS settings on your machine, so the file will be opened properly but only for you.
http://stackoverflow.com/questions/3870990/how-to-stop-visual-studio-from-opening-my-winforms-controls-in-the-designer<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fstackoverflow.com%2fquestions%2f3870990%2fhow-to-stop-visual-studio-from-opening-my-winforms-controls-in-the-designer&data=01%7c01%7craveeram%40microsoft.com%7c1ec4dc59d854489ab8f108d2dbcd7127%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=g%2bbvH4eWzyy9lS%2fzeiulyQnqxn4nHT0Y9xz32tVJ0ZE%3d>

How to fix this issue: looks like the only permanent fix is to add the below attribute to the file. See http://stackoverflow.com/questions/6256327/vs-2010-setting-non-gui-class-file-as-component<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fstackoverflow.com%2fquestions%2f6256327%2fvs-2010-setting-non-gui-class-file-as-component&data=01%7c01%7craveeram%40microsoft.com%7c1ec4dc59d854489ab8f108d2dbcd7127%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=2hPeM9Z6Wrj1Mj0VE9UHl1WUikv0yuLr1CQxAyKaqrk%3d>

[System.ComponentModel.DesignerCategory("Code")]

-

**Comment by jaredmoo** [comment]
Thanks for reporting this issue!
